version: '2'

services:
  apigateway:
    build: ./apiGateway
    ports:
      - "3000:3000"
  twittersearch:
    build: ./twitterSearch
    ports:
      - "3001:3001"
    environment:
    - PORT=3001
  twitterpost:
    build: ./twitterPost
    ports:
      - "3002:3002"
    environment:
    - PORT=3002
  twitterretweet:
    build: ./twitterRetweet
    ports:
      - "3003:3003"
    environment:
    - PORT=3003
  auth:
    build: ./auth
    ports:
      - "3004:3004"
    environment:
    - PORT=3004