version: '2'

services:
  apigateway:
    build: ./apiGateway
    ports:
      - "3000:3000"
  twittersearch:
    build: ./twitterSearch
    ports:
      - "3001:3000"
    environment:
    - PORT=3000
  twitterpost:
    build: ./twitterPost
    ports:
      - "3002:3000"
    environment:
    - PORT=3000
  twitterretweet:
    build: ./twitterRetweet
    ports:
      - "3003:3000"
    environment:
    - PORT=3000
  auth:
    build: ./auth
    ports:
      - "3004:3000"
    environment:
    - PORT=3000
  frontend:
    build: ./frontend
    ports:
      - "80:3000"